#!/usr/bin/zsh


# Automatically download the plugins manager if needed.
# I have made the conscious decision NOT to use the system package manager
# because I want this configuration to be somewhat portable (for work, where I
# won't have Archlinux for example).
ANTIDOTE="$XDG_DATA_HOME/zsh/antidote/antidote.zsh"
if [[ ! -f "$ANTIDOTE" ]]; then
    echo "Installing the Antidote plugin manager..."

    ANTIDOTE_DIR=$(dirname $ANTIDOTE)
    mkdir -p $ANTIDOTE_DIR

    git clone                                     \
        -c advice.detachedHead=false              \
        --branch=v1.10.2                          \
        --depth=1                                 \
        'https://github.com/mattmc3/antidote.git' \
        $ANTIDOTE_DIR

    echo "Antidote was installed."
fi
source "$ANTIDOTE"

# list.txt is where you specify your list of plugins.
# plugins.zsh is generated by Antidote.
antidote load "${ZDOTDIR}/plugins/list.txt" "${XDG_DATA_HOME}/antidote/plugins.zsh" 



# Plugin configuration options.
PLUGINS_DIR="${0:h}"
source "$PLUGINS_DIR/fzf-tab/fzf-tab.zsh"
source "$PLUGINS_DIR/zsh-autosuggestions.zsh"
source "$PLUGINS_DIR/zsh-bd.zsh"

